import { StyleSheet } from 'react-native'

import { colors } from '../../design/theme/colors'

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'transparent',
    zIndex: 2,
    paddingVertical: 8,
    position: 'relative',
  },
  sessionMetaRow: {
    gap: 4,
    paddingBottom: 12,
  },
  sessionMetaTitle: {
    fontSize: 32,
    lineHeight: 40,
    color: colors.textStrong,
  },
  sessionMetaDetails: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap',
  },
  sessionMetaDetailText: {
    fontSize: 16,
    lineHeight: 20,
    color: colors.text,
  },
  headerGradient: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    ...( { backgroundImage: 'linear-gradient(180deg, rgba(255,255,255,1) 0%, rgba(255,255,255,0) 100%)' } as any ),
  },
  leftHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
    marginRight: 12,
    minWidth: 0,
  },
  backTitleButton: {
    height: 40,
    borderRadius: 12,
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderColor: 'transparent',
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    alignSelf: 'flex-start',
    flexShrink: 1,
    maxWidth: '100%',
  },
  backTitleButtonHovered: {
    backgroundColor: colors.hoverBackground,
  },
  sessionTitle: {
    fontSize: 24,
    lineHeight: 28,
    color: colors.text,
    flexShrink: 1,
  },
  coacheeContainer: {
    height: 40,
    borderRadius: 12,
    backgroundColor: 'transparent',
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  coacheeContainerHovered: {
    backgroundColor: colors.hoverBackground,
  },
  coacheeName: {
    fontSize: 16,
    lineHeight: 20,
    color: colors.text,
  },
  coacheeMenu: {
    ...( { position: 'fixed', zIndex: 9999, boxShadow: '0 20px 60px rgba(0,0,0,0.16)' } as any ),
    backgroundColor: colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
    padding: 0,
    maxHeight: 48 * 7,
  },
  coacheeMenuScroll: {
    maxHeight: 48 * 7,
  },
  coacheeMenuScrollContent: {
    paddingVertical: 0,
  },
  coacheeMenuRow: {
    height: 48,
    paddingHorizontal: 24,
    flexDirection: 'row',
    alignItems: 'center',
  },
  coacheeMenuRowTop: {
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
  },
  coacheeMenuRowBottom: {
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
  },
  coacheeMenuRowHovered: {
    backgroundColor: colors.hoverBackground,
  },
  coacheeMenuRowText: {
    fontSize: 14,
    lineHeight: 18,
    color: colors.textSecondary,
  },
  coacheeMenuRowAdd: {
    backgroundColor: colors.selected,
  },
  coacheeMenuRowAddHovered: {
    backgroundColor: '#A50058',
  },
  coacheeMenuRowAddText: {
    fontSize: 14,
    lineHeight: 18,
    color: '#FFFFFF',
  },
  dateContainer: {
    height: 40,
    borderRadius: 12,
    backgroundColor: 'transparent',
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  dateContainerHovered: {
    backgroundColor: colors.hoverBackground,
  },
  dateText: {
    fontSize: 16,
    lineHeight: 20,
    color: colors.text,
  },
  titleEditorMenu: {
    ...( { position: 'fixed', zIndex: 9999, boxShadow: '0 20px 60px rgba(0,0,0,0.16)' } as any ),
    backgroundColor: colors.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  titleEditorPanelInner: {
    width: '100%',
    padding: 10,
    backgroundColor: colors.surface,
  },
  titleEditorInput: {
    width: '100%',
    height: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 12,
    fontSize: 16,
    lineHeight: 20,
    color: colors.text,
    backgroundColor: colors.surface,
  },
  dateCalendarMenu: {
    ...( { position: 'fixed', zIndex: 9999, boxShadow: '0 20px 60px rgba(0,0,0,0.16)' } as any ),
    backgroundColor: colors.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  dateCalendarPanelInner: {
    width: '100%',
    padding: 12,
    backgroundColor: colors.surface,
  },
  dateCalendarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  dateCalendarNavButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#E6C1D6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  rotatedChevron: {
    transform: [{ rotate: '180deg' }],
  },
  dateCalendarNavButtonHovered: {
    backgroundColor: '#FCEFF6',
  },
  dateCalendarNavButtonText: {
    color: colors.selected,
    fontSize: 14,
    lineHeight: 16,
  },
  dateCalendarMonthTitle: {
    fontSize: 14,
    lineHeight: 18,
    color: colors.textStrong,
    textTransform: 'capitalize',
  },
  dateCalendarWeekRow: {
    flexDirection: 'row',
    marginBottom: 6,
  },
  dateCalendarDayLabelWrap: {
    width: `${100 / 7}%` as any,
    alignItems: 'center',
  },
  dateCalendarDayLabel: {
    fontSize: 11,
    lineHeight: 14,
    color: '#777777',
    textTransform: 'uppercase',
  },
  dateCalendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    rowGap: 4,
  },
  dateCalendarDayButton: {
    width: `${100 / 7}%` as any,
    aspectRatio: 1,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dateCalendarDayButtonOutside: {
    backgroundColor: '#FAFAFA',
  },
  dateCalendarDayButtonSelected: {
    backgroundColor: colors.selected,
  },
  dateCalendarDayButtonHovered: {
    backgroundColor: '#F8E4EF',
  },
  dateCalendarDayText: {
    fontSize: 13,
    lineHeight: 16,
    color: '#1D0A00',
  },
  dateCalendarDayTextOutside: {
    color: '#999999',
  },
  dateCalendarDayTextSelected: {
    color: '#FFFFFF',
  },
  rightHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  headerActionsMenuAnchor: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    ...( { position: 'relative' } as any ),
  },
  secondaryActionButton: {
    height: 40,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: colors.border,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  secondaryActionButtonIconOnly: {
    width: 40,
    padding: 0,
  },
  secondaryActionButtonHovered: {
    backgroundColor: colors.hoverBackground,
  },
  secondaryActionText: {
    fontSize: 14,
    lineHeight: 18,
    color: '#656565',
  },
  content: {
    flex: 1,
    gap: 16,
    paddingTop: 16,
  },
  mainRow: {
    width: '100%',
    flex: 1,
    flexDirection: 'row',
    gap: 16,
    alignItems: 'stretch',
  },
  leftColumn: {
    flex: 1,
    position: 'relative',
    minHeight: 0,
  },
  rightColumn: {
    flex: 1,
  },
  leftScroll: {
    flex: 1,
    borderRadius: 12,
    overflow: 'hidden',
    ...( { overflowY: 'auto', scrollbarWidth: 'auto', scrollbarGutter: 'stable', scrollbarColor: `${colors.border} ${colors.pageBackground}` } as any ),
  },
  leftScrollGapAligned: {
    ...( { marginRight: -8, paddingRight: 8 } as any ),
  },
  leftScrollContent: {
    gap: 16,
    paddingBottom: 16,
  },
  audioCardSection: {
    width: '100%',
    gap: 8,
  },
  audioActionsRow: {
    width: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  audioActionButton: {
    height: 34,
    borderRadius: 10,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  audioActionButtonHovered: {
    backgroundColor: colors.hoverBackground,
  },
  audioActionButtonDisabled: {
    opacity: 0.55,
  },
  audioActionButtonText: {
    fontSize: 13,
    lineHeight: 16,
    color: colors.textStrong,
  },
  audioDangerButton: {
    height: 34,
    borderRadius: 10,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFF4EE',
    borderWidth: 1,
    borderColor: '#E8C2AE',
  },
  audioDangerButtonHovered: {
    backgroundColor: '#FFE7DB',
  },
  audioDangerButtonText: {
    fontSize: 13,
    lineHeight: 16,
    color: '#B85C2A',
  },
  mobileScroll: {
    flex: 1,
  },
  mobileScrollContent: {
    gap: 16,
    paddingBottom: 24,
  },
  mobileScrollContentFill: {
    flexGrow: 1,
  },
  reportCard: {
    width: '100%',
    borderRadius: 12,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 16,
  },
  reportCardFill: {
    flex: 1,
  },
  detectActivitiesCard: {
    width: '100%',
    borderRadius: 12,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 16,
    gap: 12,
  },
  detectActivitiesHeader: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  detectActivitiesTitle: {
    fontSize: 16,
    lineHeight: 20,
    color: colors.textStrong,
  },
  detectButton: {
    height: 34,
    width: 178,
    borderRadius: 10,
    backgroundColor: colors.selected,
    alignItems: 'center',
    justifyContent: 'center',
  },
  detectButtonHovered: {
    backgroundColor: '#A50058',
  },
  detectButtonDisabled: {
    opacity: 0.55,
  },
  detectButtonText: {
    fontSize: 13,
    lineHeight: 16,
    color: '#FFFFFF',
  },
  detectHelpText: {
    fontSize: 13,
    lineHeight: 18,
    color: colors.textSecondary,
  },
  detectList: {
    width: '100%',
    gap: 10,
  },
  detectItem: {
    width: '100%',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 12,
    gap: 8,
  },
  detectItemTopRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  detectItemTitle: {
    fontSize: 14,
    lineHeight: 18,
    color: colors.textStrong,
    flex: 1,
  },
  detectMetaText: {
    fontSize: 12,
    lineHeight: 16,
    color: colors.textSecondary,
  },
  detectReasonText: {
    fontSize: 13,
    lineHeight: 18,
    color: colors.text,
  },
  detectHoursRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  detectHoursInput: {
    width: 92,
    height: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: 10,
    fontSize: 13,
    lineHeight: 16,
    color: colors.textStrong,
  },
  snippetInput: {
    width: '100%',
    minHeight: 70,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 13,
    lineHeight: 18,
    color: colors.textStrong,
    textAlignVertical: 'top',
  },
  detectActionsRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  detectApproveButton: {
    height: 32,
    borderRadius: 8,
    backgroundColor: '#E6F6E6',
    borderWidth: 1,
    borderColor: '#9FD29F',
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  detectApproveButtonHovered: {
    backgroundColor: '#D8F0D8',
  },
  detectApproveButtonText: {
    fontSize: 12,
    lineHeight: 15,
    color: '#2E6A2E',
  },
  detectRejectButton: {
    height: 32,
    borderRadius: 8,
    backgroundColor: '#FFF4EE',
    borderWidth: 1,
    borderColor: '#E8C2AE',
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  detectRejectButtonHovered: {
    backgroundColor: '#FFE7DB',
  },
  detectRejectButtonText: {
    fontSize: 12,
    lineHeight: 15,
    color: '#B85C2A',
  },
  detectActionButtonDisabled: {
    opacity: 0.5,
  },
  detectDecisionText: {
    fontSize: 12,
    lineHeight: 16,
    color: colors.textSecondary,
  },
  rapportageOnlyColumn: {
    flex: 1,
    minHeight: 0,
  },
  writtenReportContainer: {
    flex: 1,
  },
  writtenReportInput: {
    width: '100%',
    height: '100%',
    padding: 0,
    fontSize: 14,
    lineHeight: 20,
    color: colors.text,
  },
  rightCard: {
    flex: 1,
    borderRadius: 12,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 16,
    gap: 16,
  },
  mobileTabsContainer: {
    width: '100%',
    backgroundColor: 'transparent',
    borderWidth: 0,
    padding: 0,
  },
  mobileTabContentCard: {
    width: '100%',
    borderRadius: 12,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 16,
    gap: 16,
  },
  mobileTabAnimated: {
    flex: 0,
  },
  chatTab: {
    flex: 1,
    gap: 16,
    position: 'relative',
  },
  chatTabMobile: {
    flex: 0,
  },
  chatArea: {
    flex: 1,
  },
  chatAreaContent: {
    gap: 12,
    paddingBottom: 8,
  },
  chatAreaMobile: {
    minHeight: 320,
  },
  chatBottom: {
    width: '100%',
    gap: 10,
  },
  noMinutesChatCtaContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 82,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: '#FFFFFF',
    padding: 12,
    paddingRight: 36,
    gap: 10,
    zIndex: 2,
  },
  noMinutesChatCtaCloseButton: {
    position: 'absolute',
    right: 8,
    top: 8,
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noMinutesChatCtaCloseButtonHovered: {
    backgroundColor: colors.hoverBackground,
  },
  noMinutesChatCtaText: {
    fontSize: 13,
    lineHeight: 18,
    color: colors.textSecondary,
  },
  noMinutesChatCtaButton: {
    alignSelf: 'flex-start',
    height: 36,
    borderRadius: 10,
    backgroundColor: colors.selected,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  noMinutesChatCtaButtonHovered: {
    backgroundColor: '#A50058',
  },
  noMinutesChatCtaButtonText: {
    fontSize: 13,
    lineHeight: 16,
    color: '#FFFFFF',
  },
  chatActionButton: {
    height: 32,
    borderRadius: 10,
    padding: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatActionButtonHovered: {
    backgroundColor: colors.hoverBackground,
  },
  chatActionText: {
    fontSize: 13,
    lineHeight: 16,
    color: colors.textSecondary,
  },
  tabsRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 12,
  },
  tabsLeft: {
    flex: 1,
    minWidth: 0,
  },
  tabsRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  chatActionsRowMobile: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  chatAreaContentCentered: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    paddingBottom: 8,
  },
  chatOverlay: {
    ...( { position: 'fixed', inset: 0, zIndex: 9999 } as any ),
    backgroundColor: 'rgba(0,0,0,0.4)',
    padding: 24,
  },
  chatOverlayCard: {
    width: '100%',
    height: '100%',
    borderRadius: 12,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 16,
    gap: 16,
  },
  chatOverlayHeader: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  chatOverlayTitle: {
    fontSize: 16,
    lineHeight: 20,
    color: colors.textStrong,
  },
  chatOverlayActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 2,
  },
  noMinutesModalContainer: {
    width: 560,
  },
  noMinutesModalContent: {
    padding: 24,
    gap: 16,
  },
  noMinutesModalTitle: {
    fontSize: 18,
    lineHeight: 22,
    color: colors.textStrong,
  },
  noMinutesModalText: {
    fontSize: 14,
    lineHeight: 20,
    color: colors.text,
  },
  noMinutesModalFooter: {
    width: '100%',
    padding: 0,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 0,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  noMinutesFooterSecondaryButton: {
    height: 48,
    borderRadius: 0,
    borderBottomLeftRadius: 16,
    backgroundColor: colors.surface,
    borderWidth: 0,
    borderColor: 'transparent',
    paddingHorizontal: 24,
    paddingVertical: 0,
    minWidth: 140,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noMinutesFooterSecondaryButtonHovered: {
    backgroundColor: colors.hoverBackground,
  },
  noMinutesFooterSecondaryButtonText: {
    fontSize: 14,
    lineHeight: 18,
    color: colors.textStrong,
  },
  noMinutesFooterPrimaryButton: {
    height: 48,
    borderRadius: 0,
    borderBottomRightRadius: 16,
    backgroundColor: colors.selected,
    paddingHorizontal: 24,
    paddingVertical: 0,
    minWidth: 140,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noMinutesFooterPrimaryButtonHovered: {
    backgroundColor: '#A50058',
  },
  noMinutesFooterPrimaryButtonText: {
    fontSize: 14,
    lineHeight: 18,
    color: '#FFFFFF',
  },
  tabAnimated: {
    flex: 1,
  },
})


