import { StyleSheet } from 'react-native'

import { colors } from '../../design/theme/colors'

export const styles = StyleSheet.create({
  overlay: {
    ...( { position: 'fixed', inset: 0, zIndex: 9000 } as any ),
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  overlayLimited: {
    padding: 0,
    alignItems: 'stretch',
    justifyContent: 'flex-start',
  },
  backdrop: {
    ...( { position: 'absolute', inset: 0 } as any ),
    backgroundColor: 'rgba(16,18,20,0.22)',
    ...( { backdropFilter: 'blur(10px)', WebkitBackdropFilter: 'blur(10px)' } as any ),
    zIndex: 0,
  },
  backdropPressable: {
    ...( { position: 'absolute', inset: 0 } as any ),
    zIndex: 0,
  },
  container: {
    width: 747,
    maxWidth: '95vw',
    height: 862,
    ...( { height: 'min(862px, 92vh)' } as any ),
    backgroundColor: colors.surface,
    borderRadius: 16,
    ...( { boxShadow: '0 2px 8px rgba(0,0,0,0.04)' } as any ),
    overflow: 'hidden',
    position: 'relative',
    zIndex: 2,
  },
  containerRecording: {
    backgroundColor: 'transparent',
    ...( { boxShadow: 'none' } as any ),
    overflow: 'visible',
  },
  containerLimited: {
    width: '100%',
    maxWidth: '100%',
    height: '100%',
    borderRadius: 0,
    backgroundColor: '#FFFFFF',
    ...( { boxShadow: 'none' } as any ),
    overflow: 'hidden',
  },
  minimizedOverlay: {
    ...( { position: 'fixed', top: 16, left: 240, right: 24, zIndex: 9000 } as any ),
    alignItems: 'flex-start',
    height: 40,
  },
  mobileTopBrand: {
    width: '100%',
    alignItems: 'center',
    paddingTop: 48,
  },
  mobileStepBrand: {
    width: '100%',
    alignItems: 'center',
    paddingTop: 20,
  },
  mobileRecordingBrand: {
    paddingTop: 8,
    marginBottom: 'auto',
  },
  mobileConsentBrand: {
    width: '100%',
    alignItems: 'center',
    paddingTop: 44,
  },
  mobileSelectBody: {
    flex: 1,
    width: '100%',
    paddingHorizontal: 24,
    paddingBottom: 24,
    justifyContent: 'space-between',
  },
  mobileSelectInfo: {
    alignItems: 'center',
    gap: 12,
  },
  mobileSelectMonitor: {
    marginTop: 8,
  },
  mobileSelectDesktopText: {
    fontSize: 18,
    lineHeight: 26,
    color: colors.textStrong,
    textAlign: 'center',
  },
  mobileSelectIllustrationWrap: {
    width: '100%',
    height: 260,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mobileSelectIllustrationCircle: {
    width: 250,
    height: 250,
    borderRadius: 125,
    backgroundColor: '#FCE3F2',
    position: 'absolute',
  },
  mobileSelectIllustrationImage: {
    width: 280,
    height: 280,
    zIndex: 1,
  },
  mobileSelectButtons: {
    gap: 12,
  },
  mobilePrimaryButton: {
    width: '100%',
    height: 56,
    borderRadius: 10,
    backgroundColor: colors.selected,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mobilePrimaryButtonHovered: {
    backgroundColor: '#A50058',
  },
  mobilePrimaryButtonText: {
    fontSize: 18,
    lineHeight: 22,
    color: '#FFFFFF',
  },
  mobileConsentBody: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingHorizontal: 20,
    paddingBottom: 24,
  },
  mobileConsentSpacer: {
    flex: 1,
  },
  mobileConsentCenter: {
    width: '100%',
    maxWidth: 520,
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 24,
  },
  mobileConsentIllustration: {
    width: 260,
    height: 260,
  },
  mobileConsentCheckboxRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  mobileConsentCheckboxLabel: {
    flex: 1,
    fontSize: 16,
    lineHeight: 24,
    color: colors.textStrong,
  },
  mobileRecordedHeader: {
    width: '100%',
    alignItems: 'center',
    gap: 14,
  },
  mobileRecordedStatusText: {
    fontSize: 20,
    lineHeight: 24,
    color: colors.textStrong,
  },
  minimizedBar: {
    width: 520,
    ...( { maxWidth: '70vw' } as any ),
    height: 40,
    borderRadius: 8,
    backgroundColor: '#F8F9F9',
    borderWidth: 1,
    borderColor: colors.border,
    padding: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  minimizedInfo: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  minimizedTimeText: {
    fontSize: 14,
    lineHeight: 18,
    color: colors.textStrong,
  },
  minimizedTimeContainer: {
    width: 64,
    alignItems: 'center',
    justifyContent: 'center',
  },
  minimizedWaveform: {
    flex: 1,
    height: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    overflow: 'hidden',
  },
  minimizedWaveBar: {
    width: 2,
    borderRadius: 8,
    backgroundColor: '#F2BBD9',
  },
  minimizedWaveBarSilent: {
    height: 2,
    borderRadius: 1,
  },
  minimizedControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  minimizedControlButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  minimizedSoftButton: {
    backgroundColor: '#FCE3F2',
  },
  minimizedSoftButtonHovered: {
    backgroundColor: '#F8D2EA',
  },
  minimizedStopButtonHovered: {
    backgroundColor: '#A50058',
  },
  minimizedStopButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.selected,
    alignItems: 'center',
    justifyContent: 'center',
  },
  minimizedPlayIconWrapper: {
    marginLeft: 2,
  },
  header: {
    width: '100%',
    height: 72,
    padding: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    position: 'relative',
    zIndex: 2,
  },
  headerTitle: {
    fontSize: 20,
    lineHeight: 24,
    color: colors.textStrong,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  recordingWarningOverlay: {
    ...( { position: 'absolute', top: 24, left: 0, right: 0, zIndex: 3 } as any ),
    alignItems: 'center',
  },
  recordingWarningBanner: {
    padding: 0,
    backgroundColor: 'transparent',
    alignItems: 'center',
    gap: 2,
  },
  recordingWarningTitle: {
    fontSize: 14,
    lineHeight: 18,
    color: colors.textStrong,
    textAlign: 'center',
  },
  recordingWarningText: {
    fontSize: 13,
    lineHeight: 17,
    color: colors.text,
    textAlign: 'center',
  },
  headerMetaText: {
    fontSize: 14,
    lineHeight: 18,
    color: colors.textStrong,
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
  },
  iconButtonHovered: {
    backgroundColor: colors.hoverBackground,
  },
  iconButtonPressed: {},
  iconButtonOverlay: {
    ...( { position: 'absolute', inset: 0 } as any ),
    backgroundColor: 'rgba(190, 1, 101, 0.08)',
  },
  body: {
    width: '100%',
    flex: 1,
    padding: 24,
    paddingBottom: 96,
    ...( { overflow: 'visible' } as any ),
    zIndex: 1,
  },
  bodyRecording: {
    padding: 0,
    paddingBottom: 0,
  },
  bodySelect: {
    paddingBottom: 0,
  },
  stepContent: {
    width: '100%',
    flex: 1,
  },
  stepScroll: {
    width: '100%',
    flex: 1,
  },
  stepScrollContent: {
    paddingBottom: 8,
  },
  stepScrollContentSelect: {
    flexGrow: 1,
  },
  selectList: {
    flex: 1,
    gap: 12,
    ...( { overflow: 'visible' } as any ),
  },
  optionRow: {
    width: '100%',
    minHeight: 84,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 20,
    borderWidth: 1,
    justifyContent: 'center',
  },
  optionRowSelected: {
    borderColor: colors.selected,
    borderWidth: 2,
  },
  optionRowUnselected: {
    borderColor: colors.border,
  },
  optionRowHovered: {
    backgroundColor: colors.hoverBackground,
  },
  optionRowContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  optionRowRightIcon: {
    marginLeft: 'auto',
  },
  optionRowText: {
    fontSize: 16,
    lineHeight: 20,
    color: colors.textStrong,
  },
  optionGroupWrap: {
    position: 'relative',
    zIndex: 1,
  },
  optionGroupWrapRaised: {
    zIndex: 25,
  },
  optionSubList: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    marginTop: 8,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    backgroundColor: colors.surface,
    overflow: 'hidden',
    ...( { boxShadow: '0 2px 8px rgba(0,0,0,0.04)' } as any ),
  },
  optionSubRow: {
    minHeight: 84,
    paddingHorizontal: 16,
    paddingVertical: 20,
    justifyContent: 'center',
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  optionSubRowFirst: {
    borderTopWidth: 0,
  },
  optionSubRowHovered: {
    backgroundColor: colors.hoverBackground,
  },
  optionSubRowText: {
    fontSize: 16,
    lineHeight: 20,
    color: colors.textStrong,
  },
  cancelButtonNoBottomLeftRadius: {
    borderBottomLeftRadius: 0,
  },
  footerFloating: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 0,
    zIndex: 2,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: '#FFFFFF',
  },
  footerInline: {
    marginTop: 16,
    paddingBottom: 0,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 0,
    zIndex: 0,
  },
  footerSplit: {
    justifyContent: 'space-between',
  },
  mobileFooterContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'column',
    paddingHorizontal: 20,
    paddingBottom: 20,
    gap: 12,
    backgroundColor: '#FFFFFF',
  },
  footerStacked: {
    flexDirection: 'column',
    alignItems: 'stretch',
    justifyContent: 'flex-end',
  },
  footerButtonBase: {
    height: 48,
    borderRadius: 0,
    paddingHorizontal: 24,
    paddingVertical: 0,
    minWidth: 180,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
  },
  footerButtonLeft: {
    borderBottomLeftRadius: 16,
  },
  footerButtonMiddle: {},
  footerButtonRight: {
    borderBottomRightRadius: 16,
  },
  footerRightGroup: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  footerRightGroupStacked: {
    width: '100%',
  },
  footerRightGroupAlignEnd: {
    marginLeft: 'auto',
  },
  mobileFooterRightGroup: {
    width: '100%',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    marginLeft: 0,
    gap: 12,
  },
  mobileFooterButtonBase: {
    width: '100%',
    minWidth: 0,
    height: 56,
    borderRadius: 10,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
  },
  mobileFooterSecondaryButton: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: colors.border,
  },
  mobileFooterPrimaryButton: {
    backgroundColor: colors.selected,
    borderWidth: 0,
  },
  mobileFooterButtonText: {
    fontSize: 18,
    lineHeight: 22,
  },
  footerButtonStackedSplit: {
    flex: 1,
    minWidth: 0,
  },
  footerButtonUploadTop: {
    width: '100%',
    borderRadius: 0,
  },
  footerButtonSecondary: {
    backgroundColor: colors.surface,
    borderWidth: 0,
    borderColor: 'transparent',
  },
  footerButtonSecondaryHovered: {
    backgroundColor: 'rgba(0,0,0,0.06)',
  },
  footerButtonSecondaryPressed: {},
  footerButtonSecondaryText: {
    fontSize: 14,
    lineHeight: 18,
    color: colors.textStrong,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  footerButtonPrimary: {
    backgroundColor: colors.selected,
  },
  footerButtonPrimaryHovered: {
    backgroundColor: '#A50058',
  },
  footerButtonPrimaryPressed: {},
  primaryButtonDisabled: {
    opacity: 0.5,
  },
  footerButtonPrimaryText: {
    fontSize: 14,
    lineHeight: 18,
    color: '#FFFFFF',
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  buttonOverlay: {
    ...( { position: 'absolute', inset: 0 } as any ),
    backgroundColor: 'rgba(190, 1, 101, 0.08)',
  },
  recordingBody: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 0,
    paddingVertical: 0,
    flex: 1,
  },
  recordingLayoutRow: {
    width: '100%',
    height: '100%',
    flexDirection: 'row',
    alignItems: 'stretch',
    justifyContent: 'center',
    gap: 24,
  },
  recordingMainCard: {
    width: 747,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#DFE0E2',
    backgroundColor: '#FFFFFF',
    ...( { boxShadow: '0 2px 8px rgba(0,0,0,0.04)' } as any ),
    overflow: 'hidden',
  },
  recordingCardHeader: {
    height: 88,
    borderBottomWidth: 1,
    borderBottomColor: '#DFE0E2',
    paddingHorizontal: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  recordingCardIdentity: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  recordingCardAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#E8D5DD',
  },
  recordingCardName: {
    fontSize: 16,
    lineHeight: 20,
    color: '#2C111F',
  },
  recordingCardInputLabel: {
    fontSize: 12,
    lineHeight: 16,
    color: '#93858D',
  },
  recordingCardMoreButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  recordingMain: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 20,
    paddingTop: 40,
    paddingBottom: 40,
  },
  recordingNotesModal: {
    width: 437,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#DFE0E2',
    backgroundColor: '#FFFFFF',
    ...( { boxShadow: '0 2px 8px rgba(0,0,0,0.04)' } as any ),
    padding: 0,
    gap: 0,
  },
  recordingNotesTitle: {
    fontSize: 24,
    lineHeight: 34,
    color: colors.textStrong,
    paddingHorizontal: 20,
    paddingTop: 22,
    paddingBottom: 18,
    borderBottomWidth: 1,
    borderBottomColor: '#DFE0E2',
  },
  recordingNotesBody: {
    fontSize: 16,
    lineHeight: 24,
    color: colors.textSecondary,
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  recordingNotesList: {
    flex: 1,
    gap: 12,
    maxHeight: '100%',
    paddingHorizontal: 20,
    paddingTop: 12,
    ...( { overflowY: 'auto' } as any ),
  },
  recordingNoteItem: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#DFE0E2',
    backgroundColor: '#F9FAFB',
    padding: 12,
    gap: 8,
  },
  recordingNoteTimestamp: {
    fontSize: 14,
    lineHeight: 16,
    color: '#0065F4',
  },
  recordingNoteTimestampPill: {
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    backgroundColor: '#EDF6FF',
  },
  recordingNoteText: {
    fontSize: 16,
    lineHeight: 24,
    color: colors.textStrong,
  },
  recordingNoteComposer: {
    marginTop: 12,
    width: '100%',
    borderTopWidth: 1,
    borderTopColor: '#DFE0E2',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 16,
  },
  recordingNoteInputWrap: {
    width: '100%',
    minHeight: 48,
    maxHeight: 132,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#DFE0E2',
    backgroundColor: '#F9FAFB',
    justifyContent: 'flex-start',
    paddingRight: 40,
    position: 'relative',
    paddingTop: 2,
  },
  recordingNoteInput: {
    width: '100%',
    minHeight: 44,
    maxHeight: 124,
    borderWidth: 0,
    borderColor: 'transparent',
    backgroundColor: 'transparent',
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 10,
    fontSize: 16,
    lineHeight: 20,
    color: colors.textStrong,
    ...( { resize: 'none' } as any ),
  },
  recordingNoteSendButton: {
    position: 'absolute',
    right: 7,
    bottom: 10,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.selected,
    alignItems: 'center',
    justifyContent: 'center',
  },
  recordingNoteSendButtonHovered: {
    backgroundColor: '#A50058',
  },
  recordingBodyLimited: {
    height: '100%',
    justifyContent: 'flex-end',
    gap: 18,
    paddingTop: 8,
    paddingBottom: 18,
  },
  waveformContainer: {
    width: '100%',
    height: 180,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 36,
    overflow: 'hidden',
  },
  waveformContainerLimited: {
    paddingHorizontal: 28,
    marginBottom: 8,
  },
  waveBar: {
    width: 8,
    borderRadius: 8,
    backgroundColor: '#F2BBD9',
  },
  timerText: {
    fontSize: 48,
    lineHeight: 56,
    color: colors.textStrong,
  },
  timerTextLimited: {
    marginBottom: 4,
  },
  recordingControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 24,
  },
  recordingControlsLimited: {
    marginTop: 'auto',
    width: '100%',
    justifyContent: 'center',
    paddingHorizontal: 28,
    marginBottom: 2,
  },
  closeWarningContainer: {
    width: 520,
  },
  closeWarningContent: {
    padding: 24,
    gap: 16,
  },
  closeWarningTitle: {
    fontSize: 18,
    lineHeight: 22,
    color: colors.textStrong,
  },
  closeWarningText: {
    fontSize: 14,
    lineHeight: 20,
    color: colors.text,
  },
  closeWarningActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 12,
  },
  closeWarningButton: {
    height: 40,
    borderRadius: 12,
    padding: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeWarningButtonSecondary: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  closeWarningButtonSecondaryHovered: {
    backgroundColor: 'rgba(0,0,0,0.06)',
  },
  closeWarningButtonSecondaryText: {
    fontSize: 14,
    lineHeight: 18,
    color: colors.textStrong,
  },
  closeWarningButtonPrimary: {
    backgroundColor: colors.selected,
  },
  closeWarningButtonPrimaryHovered: {
    backgroundColor: '#A50058',
  },
  closeWarningButtonPrimaryText: {
    fontSize: 14,
    lineHeight: 18,
    color: '#FFFFFF',
  },
  recordedCloseWarningFooter: {
    width: '100%',
    padding: 0,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 0,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  recordedCloseWarningSecondaryButton: {
    height: 48,
    borderRadius: 0,
    borderBottomLeftRadius: 16,
    backgroundColor: colors.surface,
    borderWidth: 0,
    borderColor: 'transparent',
    paddingHorizontal: 24,
    paddingVertical: 0,
    minWidth: 140,
    alignItems: 'center',
    justifyContent: 'center',
  },
  recordedCloseWarningSecondaryButtonHovered: {
    backgroundColor: colors.hoverBackground,
  },
  recordedCloseWarningSecondaryButtonText: {
    fontSize: 14,
    lineHeight: 18,
    color: colors.textStrong,
  },
  recordedCloseWarningPrimaryButton: {
    height: 48,
    borderRadius: 0,
    borderBottomRightRadius: 16,
    backgroundColor: colors.selected,
    paddingHorizontal: 24,
    paddingVertical: 0,
    minWidth: 140,
    alignItems: 'center',
    justifyContent: 'center',
  },
  recordedCloseWarningPrimaryButtonHovered: {
    backgroundColor: '#A50058',
  },
  recordedCloseWarningPrimaryButtonText: {
    fontSize: 14,
    lineHeight: 18,
    color: '#FFFFFF',
  },
  insufficientMinutesModalContainer: {
    width: 560,
  },
  insufficientMinutesModalContent: {
    padding: 24,
    gap: 16,
  },
  insufficientMinutesModalTitle: {
    fontSize: 18,
    lineHeight: 22,
    color: colors.textStrong,
  },
  insufficientMinutesModalText: {
    fontSize: 14,
    lineHeight: 20,
    color: colors.text,
  },
  insufficientMinutesFooter: {
    width: '100%',
    padding: 0,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 0,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  insufficientMinutesFooterSecondaryButton: {
    height: 48,
    borderRadius: 0,
    borderBottomLeftRadius: 16,
    backgroundColor: colors.surface,
    borderWidth: 0,
    borderColor: 'transparent',
    paddingHorizontal: 24,
    paddingVertical: 0,
    minWidth: 180,
    alignItems: 'center',
    justifyContent: 'center',
  },
  insufficientMinutesFooterSecondaryButtonHovered: {
    backgroundColor: colors.hoverBackground,
  },
  insufficientMinutesFooterSecondaryButtonText: {
    fontSize: 14,
    lineHeight: 18,
    color: colors.textStrong,
  },
  insufficientMinutesFooterPrimaryButton: {
    height: 48,
    borderRadius: 0,
    borderBottomRightRadius: 16,
    backgroundColor: colors.selected,
    paddingHorizontal: 24,
    paddingVertical: 0,
    minWidth: 180,
    alignItems: 'center',
    justifyContent: 'center',
  },
  insufficientMinutesFooterPrimaryButtonHovered: {
    backgroundColor: '#A50058',
  },
  insufficientMinutesFooterPrimaryButtonText: {
    fontSize: 14,
    lineHeight: 18,
    color: '#FFFFFF',
  },
  softCircle: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: '#FCE3F2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  softCircleHovered: {
    backgroundColor: '#F8D2EA',
  },
  primaryCircle: {
    width: 92,
    height: 92,
    borderRadius: 46,
    backgroundColor: colors.selected,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryCircleHovered: {
    backgroundColor: '#A50058',
  },
  softCircleLimited: {
    width: 62,
    height: 62,
    borderRadius: 31,
  },
  primaryCircleLimited: {
    width: 82,
    height: 82,
    borderRadius: 41,
  },
  recordedBody: {
    width: '100%',
    gap: 16,
  },
  recordedDropdownsRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  recordedDropdownsColumn: {
    flexDirection: 'column',
  },
  audioPreviewCard: {
    width: '100%',
    padding: 0,
    position: 'relative',
  },
  footerButtonCompact: {
    minWidth: 0,
    flex: 1,
    paddingHorizontal: 12,
  },
  audioSaveToggleRow: {
    position: 'absolute',
    right: 12,
    bottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.92)',
  },
  audioSaveToggleRowHovered: {
    backgroundColor: 'rgba(249,249,249,0.98)',
  },
  audioSaveToggleLabel: {
    fontSize: 12,
    lineHeight: 16,
    color: colors.textStrong,
  },
  audioSaveToggleTrack: {
    width: 34,
    height: 20,
    borderRadius: 999,
    paddingHorizontal: 2,
    justifyContent: 'center',
  },
  audioSaveToggleTrackOff: {
    backgroundColor: '#D2D2D2',
  },
  audioSaveToggleTrackOn: {
    backgroundColor: colors.selected,
  },
  audioSaveToggleThumb: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
  },
  audioSaveToggleThumbOff: {
    alignSelf: 'flex-start',
  },
  audioSaveToggleThumbOn: {
    alignSelf: 'flex-end',
  },
  uploadBody: {
    width: '100%',
    gap: 16,
  },
  consentBody: {
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 16,
    paddingTop: 8,
  },
  consentIconCircle: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: '#FCE3F2',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  consentTitle: {
    fontSize: 30,
    lineHeight: 36,
    color: colors.textStrong,
    textAlign: 'center',
  },
  consentTitleCompact: {
    fontSize: 22,
    lineHeight: 30,
  },
  consentDescription: {
    fontSize: 15,
    lineHeight: 22,
    color: colors.text,
    textAlign: 'center',
    maxWidth: 640,
  },
  consentDescriptionCompact: {
    fontSize: 14,
    lineHeight: 21,
  },
  consentCheckboxRow: {
    width: '100%',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 8,
  },
  consentCheckboxRowHovered: {
    backgroundColor: colors.hoverBackground,
  },
  consentCheckbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    flexShrink: 0,
  },
  consentCheckboxChecked: {
    borderColor: '#FFFFFF',
    backgroundColor: '#FFFFFF',
  },
  consentCheckboxLabel: {
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
    color: colors.textStrong,
  },
  consentHelpLinkRow: {
    marginTop: 2,
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 8,
  },
  consentHelpLinkRowHovered: {
    backgroundColor: colors.hoverBackground,
  },
  consentHelpLinkText: {
    fontSize: 14,
    lineHeight: 20,
    color: colors.selected,
    textDecorationLine: 'underline',
  },
  uploadDropArea: {
    width: '100%',
    borderRadius: 12,
    backgroundColor: '#F0F0F0',
    borderWidth: 1,
    borderColor: colors.border,
    padding: 24,
    height: 320,
    alignItems: 'center',
    justifyContent: 'center',
  },
  uploadPressable: {
    width: '100%',
    height: '100%',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  uploadDropAreaHovered: {
    backgroundColor: colors.hoverBackground,
  },
  uploadDropAreaActive: {
    backgroundColor: 'rgba(190,1,101,0.08)',
    borderColor: colors.selected,
  },
  uploadCenter: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  uploadHintText: {
    fontSize: 14,
    lineHeight: 18,
    color: colors.textStrong,
  },
  uploadFileNameText: {
    fontSize: 14,
    lineHeight: 18,
    color: '#656565',
    maxWidth: 520,
    textAlign: 'center',
  },
  uploadDurationWarningText: {
    fontSize: 13,
    lineHeight: 18,
    color: colors.selected,
    maxWidth: 700,
    textAlign: 'center',
  },
  footerButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  dropdownArea: {
    width: '100%',
    position: 'relative',
    zIndex: 1,
  },
  dropdownAreaHalf: {
    flex: 1,
    width: undefined as any,
  },
  dropdownAreaRaised: {
    zIndex: 2,
  },
  infoRow: {
    width: '100%',
    height: 64,
    borderRadius: 12,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  infoRowHovered: {
    backgroundColor: colors.hoverBackground,
  },
  infoRowText: {
    fontSize: 16,
    lineHeight: 20,
    color: colors.textStrong,
  },
  infoRowSpacer: {
    flex: 1,
  },
  sessionTitleInput: {
    flex: 1,
    paddingHorizontal: 0,
    paddingTop: 2,
    paddingBottom: 2,
    minHeight: 32,
    fontSize: 16,
    lineHeight: 24,
    color: colors.textStrong,
    textAlignVertical: 'center',
  },
  clientPanel: {
    width: '100%',
    position: 'absolute',
    left: 0,
    right: 0,
    top: 72,
    borderRadius: 16,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 0,
    gap: 0,
    ...( { boxShadow: '0 2px 8px rgba(0,0,0,0.04)' } as any ),
    zIndex: 30,
    overflow: 'hidden',
  },
  reportTypePanel: {
    width: '100%',
    position: 'absolute',
    left: 0,
    right: 0,
    top: 72,
    borderRadius: 16,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 0,
    gap: 0,
    ...( { boxShadow: '0 2px 8px rgba(0,0,0,0.04)' } as any ),
    zIndex: 30,
    overflow: 'hidden',
  },
  reportTypeList: {
    width: '100%',
  },
  reportTypeListContent: {
    paddingVertical: 0,
  },
  reportTypeItem: {
    width: '100%',
    height: 48,
    paddingHorizontal: 24,
    justifyContent: 'center',
  },
  reportTypeItemTop: {
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
  },
  reportTypeItemBottom: {
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
  },
  reportTypeItemHovered: {
    backgroundColor: colors.hoverBackground,
  },
  reportTypeItemText: {
    fontSize: 14,
    lineHeight: 18,
    color: colors.textStrong,
  },
  clientList: {
    width: '100%',
  },
  clientListContent: {
    paddingVertical: 0,
  },
  clientItem: {
    width: '100%',
    height: 48,
    paddingHorizontal: 24,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  clientItemTop: {
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
  },
  clientItemBottom: {
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
  },
  clientItemHovered: {
    backgroundColor: colors.hoverBackground,
  },
  clientItemText: {
    fontSize: 14,
    lineHeight: 18,
    color: colors.textStrong,
  },
  clientItemAdd: {
    backgroundColor: colors.selected,
  },
  clientItemAddHovered: {
    backgroundColor: '#A50058',
  },
  clientItemAddText: {
    fontSize: 14,
    lineHeight: 18,
    color: '#FFFFFF',
  },
})











