export { createClient, updateClient, deleteClient } from "./mutations/clients"
export { createSession, updateSession, deleteSession } from "./mutations/sessions"
export { createNote, updateNote, deleteNote } from "./mutations/notes"
export { setWrittenReport } from "./mutations/writtenReports"
export { createTrajectory, updateTrajectory, deleteTrajectory } from "./mutations/trajectories"
export { createActivity, updateActivity, deleteActivity } from "./mutations/activities"
export { createActivityTemplate, updateActivityTemplate, deleteActivityTemplate } from "./mutations/activityTemplates"
export { createSnippet, updateSnippet, deleteSnippet } from "./mutations/snippets"
export { createTemplate, updateTemplate, deleteTemplate } from "./mutations/templates"
export { updatePracticeSettings } from "./mutations/practiceSettings"

