import { StyleSheet } from 'react-native'

import { colors } from '@/design/theme/colors'
import { typography } from '@/design/theme/typography'

export const styles = StyleSheet.create({
  scroll: {
    flex: 1,
    minHeight: 0,
  },
  content: {
    paddingTop: 24,
    paddingHorizontal: 24,
    paddingBottom: 32,
    gap: 24,
  },
  heroCard: {
    width: '100%',
    height: 128,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#7E0056',
    backgroundColor: colors.selected,
    ...( { backgroundImage: 'linear-gradient(101deg,#BE0165 0%,#7E0056 100%)' } as any ),
    paddingHorizontal: 28,
    paddingVertical: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    ...( { boxShadow: '0 2px 8px rgba(0,0,0,0.04)' } as any ),
  },
  heroTextWrap: {
    flex: 1,
    gap: 8,
  },
  heroTitle: {
    fontSize: 32,
    lineHeight: 40,
    color: '#FFFFFF',
    fontFamily: typography.fontFamilySemibold,
  },
  heroSubtitle: {
    fontSize: 16,
    lineHeight: 24,
    color: '#FFFFFF',
    fontFamily: typography.fontFamilyMedium,
  },
  heroButton: {
    width: 168,
    height: 40,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#FFFFFF',
    backgroundColor: 'transparent',
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  heroButtonHovered: {
    backgroundColor: 'rgba(255,255,255,0.12)',
  },
  heroButtonText: {
    fontSize: 16,
    lineHeight: 20,
    color: '#FFFFFF',
    fontFamily: typography.fontFamilyRegular,
  },
  topGrid: {
    flexDirection: 'row',
    gap: 24,
  },
  statsGrid: {
    flexDirection: 'row',
    gap: 24,
    flexWrap: 'wrap',
  },
  statCard: {
    flex: 1,
    minWidth: 248,
    height: 120,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#DFE0E2',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 24,
    position: 'relative',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    ...( { boxShadow: '0 2px 8px rgba(0,0,0,0.04)' } as any ),
  },
  statCardInteractive: {
    cursor: 'pointer' as any,
  },
  statCardHovered: {
    backgroundColor: '#FCFCFD',
  },
  statCardPressed: {
    backgroundColor: '#F4F5F7',
  },
  statCardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  statCardTitle: {
    flex: 1,
    fontSize: 16,
    lineHeight: 22,
    color: '#2C111F',
    fontFamily: typography.fontFamilySemibold,
  },
  statCardIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statCardValueRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 8,
    position: 'absolute',
    left: 24,
    bottom: 24,
  },
  statCardValue: {
    fontSize: 32,
    lineHeight: 40,
    color: '#2C111F',
    fontFamily: typography.fontFamilyBold,
  },
  statCardSuffix: {
    fontSize: 16,
    lineHeight: 22,
    color: '#93858D',
    fontFamily: typography.fontFamilyMedium,
  },
  topGridStacked: {
    flexDirection: 'column',
  },
  panelCard: {
    flex: 1,
    minWidth: 340,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#DFE0E2',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
    paddingVertical: 18,
    gap: 16,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    ...( { boxShadow: '0 2px 8px rgba(0,0,0,0.04)' } as any ),
  },
  panelTitle: {
    fontSize: 24,
    lineHeight: 32,
    color: '#2C111F',
    fontFamily: typography.fontFamilySemibold,
  },
  panelList: {
    gap: 12,
  },
  listRow: {
    height: 64,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E6E7',
    backgroundColor: '#F9FAFB',
    paddingHorizontal: 14,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  listRowHovered: {
    backgroundColor: colors.hoverBackground,
  },
  quickIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  avatarWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F6F6F6',
    borderWidth: 1,
    borderColor: '#DADBDD',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },
  avatarFallbackText: {
    fontSize: 16,
    lineHeight: 20,
    color: '#2C111F',
  },
  listRowTextWrap: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  listRowTitle: {
    fontSize: 16,
    lineHeight: 22,
    color: '#2C111F',
    fontFamily: typography.fontFamilySemibold,
  },
  listRowSubtitle: {
    fontSize: 14,
    lineHeight: 18,
    color: 'rgba(44,17,31,0.55)',
    fontFamily: typography.fontFamilySemibold,
  },
  emptyPanelState: {
    minHeight: 120,
    borderWidth: 1,
    borderColor: '#DFE0E2',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyPanelText: {
    fontSize: 16,
    lineHeight: 20,
    color: 'rgba(44,17,31,0.55)',
  },
  tableCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#DFE0E2',
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    ...( { boxShadow: '0 2px 8px rgba(0,0,0,0.04)' } as any ),
  },
  tableHeaderTop: {
    borderBottomWidth: 1,
    borderBottomColor: '#DFE0E2',
    paddingLeft: 24,
    paddingRight: 24,
    paddingTop: 24,
    paddingBottom: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    flexWrap: 'wrap',
  },
  tableHeading: {
    fontSize: 24,
    lineHeight: 32,
    color: '#2C111F',
    fontFamily: typography.fontFamilySemibold,
  },
  tableSearchBar: {
    width: 296,
    maxWidth: '100%',
  },
  tableHeaderRow: {
    minHeight: 68,
    borderBottomWidth: 1,
    borderBottomColor: '#DFE0E2',
    backgroundColor: '#F9FAFB',
    paddingLeft: 24,
    paddingRight: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  tableHeaderText: {
    fontSize: 16,
    lineHeight: 20,
    color: 'rgba(44,17,31,0.5)',
    fontFamily: typography.fontFamilySemibold,
  },
  tableBody: {
    minHeight: 120,
  },
  tableRow: {
    minHeight: 56,
    borderBottomWidth: 1,
    borderBottomColor: '#DFE0E2',
    paddingLeft: 24,
    paddingRight: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  tableRowHovered: {
    backgroundColor: colors.hoverBackground,
  },
  tableRowDisabled: {
    opacity: 0.55,
  },
  tableCell: {
    justifyContent: 'center',
  },
  itemCell: {
    flex: 1.8,
    minWidth: 320,
  },
  clientCell: {
    flex: 1.2,
    minWidth: 180,
  },
  createdCell: {
    width: 160,
  },
  statusCell: {
    width: 170,
  },
  updatedCell: {
    width: 160,
  },
  chevronCell: {
    width: 24,
    alignItems: 'center',
  },
  tableItemText: {
    fontSize: 16,
    lineHeight: 20,
    color: '#2C111F',
  },
  tableClientName: {
    fontSize: 16,
    lineHeight: 20,
    color: '#2C111F',
  },
  tableSecondaryText: {
    fontSize: 16,
    lineHeight: 20,
    color: colors.textSecondary,
  },
  statusPill: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    alignSelf: 'flex-start',
  },
  statusPillReview: {
    backgroundColor: '#FEF3C7',
  },
  statusPillPending: {
    backgroundColor: '#EAF2FF',
  },
  statusPillText: {
    fontSize: 12,
    lineHeight: 14,
  },
  statusPillTextReview: {
    color: '#B45309',
  },
  statusPillTextPending: {
    color: '#1D4ED8',
  },
  emptyTableState: {
    minHeight: 100,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  emptyTableText: {
    fontSize: 16,
    lineHeight: 20,
    color: 'rgba(44,17,31,0.55)',
  },
})
